#!/bin/sh

# wait for controllers to finish logging this minute data
sleep 30

# heating data import
heatinglog=/home/den/Shden/shc/log/heating.log
#tmp=/home/den/Shden/shc/log/heating.tmp

#mv $heatinglog $tmp -f
#mysqlimport -L -u importuser -pimportuser --fields-terminated-by="|" SHDEN $tmp
rm $heatinglog -f

# humidity data import
humiditylog=/home/den/Shden/shc/log/ventilation.log
tmphumidity=/home/den/Shden/shc/log/humidity.tmp

mv $humiditylog $tmphumidity -f
mysqlimport -L -u importuser -pimportuser --fields-terminated-by="|" SHDEN $tmphumidity
rm $tmphumidity

# power data import
powerlog=/home/den/Shden/shc/log/power.log
tmppower=/home/den/Shden/shc/log/power.tmp

mv $powerlog $tmppower -f
mysqlimport -L -u importuser -pimportuser --fields-terminated-by="," SHDEN $tmppower
rm $tmppower
