#!/bin/sh

heatinglog=/home/den/Shden/shc/log/heating.log
tmp=/home/den/Shden/shc/log/heating.tmp

mv $heatinglog $tmp -f
mysqlimport -L -u root -pexpress --fields-terminated-by="|" SHDEN $tmp
rm $tmp -f

