DELIMITER //
DROP PROCEDURE IF EXISTS SP_GET_POWER_STATISTICS;
CREATE PROCEDURE SP_GET_POWER_STATISTICS() 
BEGIN
	SELECT	DATE(time) AS DATE,
		MIN(U1) AS U1_MIN,
		MAX(U1) AS U1_MAX,
		AVG(U1) AS U1_AVG,
		STD(U1) AS U1_STD,
		MIN(U2) AS U2_MIN,
		MAX(U2) AS U2_MAX,
		AVG(U2) AS U2_AVG,
		STD(U2) AS U2_STD,
		MIN(U3) AS U3_MIN,
		MAX(U3) AS U3_MAX,
		AVG(U3) AS U3_AVG,
		STD(U3) AS U3_STD,
		SUM(CASE WHEN U1 < 207 OR U2 < 207 OR U3 < 207 THEN 1 ELSE 0 END) AS LowVoltageMinutes,
		SUM(CASE WHEN U1 > 253 OR U2 > 253 OR U3 > 253 THEN 1 ELSE 0 END) AS HighVoltageMinutes,
		SUM(CASE WHEN U1 = 0 OR U2 = 0 OR U3 =0 THEN 1 ELSE 0 END) AS CutoffMinutes
	FROM	power
	GROUP BY DATE(time);
END//
DELIMITER ;
