#!/bin/sh

log="${PWD}/events.log"

case "$1" in

	sunraise)
		echo "[$(date)]: Sunraise" >> $log
		echo 0 >> ${PWD}/../appliances/streetLight1
		echo "  Street light turned off." >> $log
		;;

	sunset)
		echo "[$(date)]: Sunset" >> $log
		echo 1 >> ${PWD}/../appliances/streetLight1
		echo "  Street light turned on." >> $log
		;;

	*)
		echo "[$(date)]: Unknown event [$1], cannot route." >> $log
		exit 1
esac
