#!/bin/sh

DIR="/home/den/Shden"
log="$DIR/events/events.log"

case "$1" in

	sunraise)
		echo "[$(date)]: Sunraise" >> $log
		echo 0 >> $DIR/appliances/streetLight250
		echo "  Street light turned off." >> $log
		;;

	sunset)
		echo "[$(date)]: Sunset" >> $log
		echo 1 >> $DIR/appliances/streetLight250
		echo "  Street light turned on." >> $log
		;;

	*)
		echo "[$(date)]: Unknown event [$1], cannot route." >> $log
		exit 1
esac
